services:
  db:
    build:
      context: ../../
      dockerfile: CA2/part4/db.Dockerfile
    image: part4-db:db
    container_name: h2_database
    ports:
      - "8082:8082"  # H2 Web Console
      - "9092:9092"  # H2 TCP Server
    volumes:
          - ./db-data:/usr/src/data-backup
    networks:
      - app-network

  web:
    build:
      context: ../../
      dockerfile: CA2/part4/web.Dockerfile
    image: part4-web:web
    container_name: web_app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:h2:tcp://db:9092/~/test
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD:
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
